spring.datasource.url=jdbc:mysql://localhost:3306/testdb_spring?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Nishant@2611

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
ml.server.url=http://localhost:5000

# JWT Properties
bezkoder.app.jwtCookieName=bezkoder
bezkoder.app.jwtSecret======================BezKoder=Spring===========================
bezkoder.app.jwtExpirationMs=86400000